/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.queue.category;

import com.rameses.queue.section.*;
import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author Dino Quimson
 */
@Template(FormPage.class)
@StyleSheet
public class QueueCategoryPage extends javax.swing.JPanel {

    /**
     * Creates new form QueueSectionPage
     */
    public QueueCategoryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();

        xFormPanel1.setCaptionWidth(120);

        xTextField1.setCaption("Name");
        xTextField1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField1.setName("entity.name"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 22));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xTextField2.setCaption("Prefix");
        xTextField2.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField2.setName("entity.prefix"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(100, 22));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xIntegerField1.setText("xIntegerField1");
        xIntegerField1.setCaption("Sort Order");
        xIntegerField1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField1.setName("entity.sortorder"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(50, 22));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
