/*
 * MakePage.java
 *
 * Created on May 26, 2014, 2:11 PM
 */

package com.rameses.gov.mtop.unitype;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  arnel
 */
@Template(FormPage.class)
@StyleSheet()
public class UnitTypePage extends javax.swing.JPanel {
    
    /** Creates new form UnitTypePage */
    public UnitTypePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel5 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        jLabel1 = new javax.swing.JLabel();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Unit Type Information");
        jPanel5.setBorder(xTitledBorder1);

        formPanel1.setBorder(null);
        formPanel1.setCaptionWidth(85);
        xTextField2.setCaption("Prefix Code");
        xTextField2.setCaptionWidth(100);
        xTextField2.setDepends(new String[] {"selectedItem"});
        xTextField2.setName("entity.prefixcode");
        xTextField2.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xTextField3.setCaption("Prefix Name");
        xTextField3.setCaptionWidth(100);
        xTextField3.setDepends(new String[] {"selectedItem"});
        xTextField3.setName("entity.prefixname");
        xTextField3.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);

        xComboBox1.setCaption("Suffix Type");
        xComboBox1.setCaptionWidth(100);
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("suffixTypes");
        xComboBox1.setName("entity.suffixtype");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xComboBox1);

        xTextField6.setCaption("Suffix Name");
        xTextField6.setCaptionWidth(100);
        xTextField6.setDepends(new String[] {"suffixtype"});
        xTextField6.setName("entity.suffixname");
        xTextField6.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xTextField6);

        xNumberField1.setCaption("No. of Digits");
        xNumberField1.setCaptionWidth(100);
        xNumberField1.setDepends(new String[] {"selectedItem"});
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        xNumberField1.setName("entity.franchisedigitno");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xNumberField1.setRequired(true);
        formPanel1.add(xNumberField1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Franchise No. Setting");
        jLabel1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());

        formPanel2.setBorder(null);
        formPanel2.setCaptionWidth(85);
        xTextField4.setCaption("Code");
        xTextField4.setCaptionWidth(100);
        xTextField4.setDepends(new String[] {"selectedItem"});
        xTextField4.setName("entity.code");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField4.setRequired(true);
        formPanel2.add(xTextField4);

        xTextField5.setCaption("Name");
        xTextField5.setCaptionWidth(100);
        xTextField5.setDepends(new String[] {"selectedItem"});
        xTextField5.setName("entity.name");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField5.setRequired(true);
        formPanel2.add(xTextField5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(formPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(formPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    // End of variables declaration//GEN-END:variables
    
}
