/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.waterworks.meter;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author Dino Quimson
 */
@Template(FormPage.class)
@StyleSheet
public class MeterPage extends javax.swing.JPanel {

    /**
     * Creates new form MeterPage
     */
    public MeterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();

        xFormPanel1.setCaptionWidth(150);

        xTextField1.setCaption("Serial Prefix");
        xTextField1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField1.setName("entity.prefix"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(120, 22));
        xFormPanel1.add(xTextField1);

        xIntegerField1.setCaption("Serial Start Series");
        xIntegerField1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField1.setName("entity.startseries"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(120, 20));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xIntegerField2.setCaption("Serial End Series");
        xIntegerField2.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField2.setName("entity.endseries"); // NOI18N
        xIntegerField2.setPreferredSize(new java.awt.Dimension(120, 20));
        xIntegerField2.setRequired(true);
        xFormPanel1.add(xIntegerField2);

        xTextField4.setCaption("Brand");
        xTextField4.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField4.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xTextField4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField4.setName("entity.brand"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 22));
        xTextField4.setRequired(true);
        xFormPanel1.add(xTextField4);

        xTextField5.setCaption("Capacity");
        xTextField5.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField5.setName("entity.capacity"); // NOI18N
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 22));
        xTextField5.setRequired(true);
        xFormPanel1.add(xTextField5);

        xComboBox1.setCaption("Size");
        xComboBox1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox1.setExpression("#{item.metersize}");
        xComboBox1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox1.setItems("sizes");
        xComboBox1.setName("entity.metersize"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(120, 22));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
}
