/*
 * OrderOfDroppingPrivateUnitPage.java
 *
 * Created on June 9, 2014, 4:19 PM
 */

package com.rameses.gov.etracs.mtop.orderofdropping;

/**
 *
 * @author  arnel
 */
public class OrderOfDroppingPrivateUnitPage extends javax.swing.JPanel {
    
    /** Creates new form OrderOfDroppingPrivateUnitPage */
    public OrderOfDroppingPrivateUnitPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        formPanel9 = new com.rameses.rcp.util.FormPanel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        jPanel3 = new javax.swing.JPanel();
        formPanel6 = new com.rameses.rcp.util.FormPanel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        formPanel8 = new com.rameses.rcp.util.FormPanel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();

        jPanel2.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("General Information");
        jPanel2.setBorder(xTitledBorder1);
        formPanel5.setPadding(new java.awt.Insets(5, 5, 0, 5));
        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel6.setBorder(xLineBorder1);
        xLabel6.setCaption("Franchise No.");
        xLabel6.setCaptionWidth(95);
        xLabel6.setExpression("#{entity.franchiseno}");
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 19));

        com.rameses.rcp.control.border.XLineBorder xLineBorder2 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder2.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel3.setBorder(xLineBorder2);
        xLabel3.setCaption("Type");
        xLabel3.setCaptionWidth(95);
        xLabel3.setExpression("#{entity.type}");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 19));

        javax.swing.GroupLayout formPanel5Layout = new javax.swing.GroupLayout(formPanel5);
        formPanel5.setLayout(formPanel5Layout);
        formPanel5Layout.setHorizontalGroup(
            formPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(formPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        formPanel5Layout.setVerticalGroup(
            formPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(xLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2.add(formPanel5);
        formPanel5.setBounds(10, 20, 290, 50);

        formPanel9.setPadding(new java.awt.Insets(5, 5, 0, 5));
        com.rameses.rcp.control.border.XLineBorder xLineBorder3 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder3.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel4.setBorder(xLineBorder3);
        xLabel4.setCaption("State");
        xLabel4.setCaptionWidth(80);
        xLabel4.setExpression("#{entity.state}");
        xLabel4.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel9.add(xLabel4);

        xDateField2.setCaption("Date");
        xDateField2.setCaptionWidth(80);
        xDateField2.setEnabled(false);
        xDateField2.setName("entity.txndate");
        xDateField2.setOpaque(false);
        xDateField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xDateField2.setRequired(true);
        formPanel9.add(xDateField2);

        jPanel2.add(formPanel9);
        formPanel9.setBounds(300, 20, 260, 50);

        formPanel1.setCellpadding(new java.awt.Insets(0, 0, 0, 5));
        formPanel1.setPadding(new java.awt.Insets(0, 5, 5, 5));
        com.rameses.rcp.control.border.XLineBorder xLineBorder4 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder4.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel1.setBorder(xLineBorder4);
        xLabel1.setCaption("Owner Name");
        xLabel1.setCaptionWidth(95);
        xLabel1.setExpression("#{entity.owner.name}");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel1);

        com.rameses.rcp.control.border.XLineBorder xLineBorder5 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder5.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel2.setBorder(xLineBorder5);
        xLabel2.setCaption("Owner Address");
        xLabel2.setCaptionWidth(95);
        xLabel2.setExpression("#{entity.owner.address}");
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel2);

        jPanel2.add(formPanel1);
        formPanel1.setBounds(10, 70, 550, 45);

        formPanel2.setPadding(new java.awt.Insets(1, 5, 5, 5));
        xTextField3.setCaption("CTC No.");
        xTextField3.setCaptionWidth(95);
        xTextField3.setIndex(-1);
        xTextField3.setName("entity.ctcno");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField3.setRequired(true);
        formPanel2.add(xTextField3);

        jPanel2.add(formPanel2);
        formPanel2.setBounds(10, 110, 290, 25);

        formPanel4.setPadding(new java.awt.Insets(1, 5, 5, 5));
        xDateField1.setCaption("CTC Date");
        xDateField1.setCaptionWidth(80);
        xDateField1.setName("entity.ctcdateissued");
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xDateField1.setRequired(true);
        formPanel4.add(xDateField1);

        jPanel2.add(formPanel4);
        formPanel4.setBounds(300, 110, 260, 25);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Unit Information");
        jPanel3.setBorder(xTitledBorder2);

        com.rameses.rcp.control.border.XLineBorder xLineBorder6 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder6.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel11.setBorder(xLineBorder6);
        xLabel11.setCaption("Unit Type");
        xLabel11.setCaptionWidth(95);
        xLabel11.setExpression("#{entity.unittype}");
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xLabel11);

        com.rameses.rcp.control.border.XLineBorder xLineBorder7 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder7.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel12.setBorder(xLineBorder7);
        xLabel12.setCaption("Make");
        xLabel12.setCaptionWidth(95);
        xLabel12.setExpression("#{entity.make}");
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xLabel12);

        com.rameses.rcp.control.border.XLineBorder xLineBorder8 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder8.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel7.setBorder(xLineBorder8);
        xLabel7.setCaption("Model");
        xLabel7.setCaptionWidth(95);
        xLabel7.setExpression("#{entity.model}");
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xLabel7);

        com.rameses.rcp.control.border.XLineBorder xLineBorder9 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder9.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel8.setBorder(xLineBorder9);
        xLabel8.setCaption("Motor No.");
        xLabel8.setExpression("#{entity.motorno}");
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel8.add(xLabel8);

        com.rameses.rcp.control.border.XLineBorder xLineBorder10 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder10.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel13.setBorder(xLineBorder10);
        xLabel13.setCaption("Chassis No.");
        xLabel13.setExpression("#{entity.chassisno}");
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel8.add(xLabel13);

        com.rameses.rcp.control.border.XLineBorder xLineBorder11 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder11.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel14.setBorder(xLineBorder11);
        xLabel14.setCaption("Plate No.");
        xLabel14.setExpression("#{entity.plateno}");
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel8.add(xLabel14);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.util.FormPanel formPanel6;
    private com.rameses.rcp.util.FormPanel formPanel8;
    private com.rameses.rcp.util.FormPanel formPanel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
    
}
