/*
 * SubdivisionPage.java
 *
 * Created on July 1, 2011, 4:55 PM
 */

package com.rameses.gov.etracs.rpt.subdivision.ui;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  rameses
 */
@Template(FormPage.class)
public class SubdivisionInfoMainPage extends javax.swing.JPanel {
    
    /** Creates new form SubdivisionPage */
    public SubdivisionInfoMainPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xLabel15 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xLabel18 = new com.rameses.rcp.control.XLabel();
        xLabel17 = new com.rameses.rcp.control.XLabel();
        xLabel19 = new com.rameses.rcp.control.XLabel();
        xLabel20 = new com.rameses.rcp.control.XLabel();
        xLabel21 = new com.rameses.rcp.control.XLabel();
        xLabel16 = new com.rameses.rcp.control.XLabel();
        xLabel25 = new com.rameses.rcp.control.XLabel();
        xLabel26 = new com.rameses.rcp.control.XLabel();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Subdivision Information");
        formPanel3.setBorder(xTitledBorder1);
        formPanel3.setCaptionWidth(95);

        xLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel15.setCaption("Tracking No.");
        xLabel15.setCaptionWidth(115);
        xLabel15.setExpression("#{entity.trackingno}");
        xLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        xLabel15.setForeground(new java.awt.Color(153, 0, 0));
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 21));
        formPanel3.add(xLabel15);

        xLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel3.setCaption("Revision Year");
        xLabel3.setCaptionWidth(115);
        xLabel3.setExpression("#{entity.ry}");
        xLabel3.setPreferredSize(new java.awt.Dimension(130, 19));
        formPanel3.add(xLabel3);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Mother FAAS Information");
        formPanel5.setBorder(xTitledBorder2);
        formPanel5.setCellspacing(1);
        formPanel5.setPreferredSize(new java.awt.Dimension(120, 80));

        xFormPanel1.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel1.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel1.setPreferredSize(new java.awt.Dimension(0, 23));
        xFormPanel1.setShowCaption(false);

        xButton1.setCellPadding(new java.awt.Insets(0, 0, 0, 20));
        xButton1.setEnabled(false);
        xButton1.setName("viewMotherFaas"); // NOI18N
        xButton1.setShowCaption(false);
        xButton1.setText("  TD No.  ");
        xFormPanel1.add(xButton1);

        xLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel18.setCaption("TD No.");
        xLabel18.setCaptionWidth(100);
        xLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xLabel18.setName("entity.motherfaas.tdno"); // NOI18N
        xLabel18.setPreferredSize(new java.awt.Dimension(0, 22));
        xLabel18.setShowCaption(false);
        xFormPanel1.add(xLabel18);

        formPanel5.add(xFormPanel1);

        xLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel17.setCaption("Owner");
        xLabel17.setCaptionWidth(100);
        xLabel17.setName("entity.motherfaas.owner.name"); // NOI18N
        xLabel17.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xLabel17);

        xLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel19.setCaption("Address");
        xLabel19.setCaptionWidth(100);
        xLabel19.setName("entity.motherfaas.owner.address"); // NOI18N
        xLabel19.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xLabel19);

        xLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel20.setCaption("Administrator");
        xLabel20.setCaptionWidth(100);
        xLabel20.setName("entity.motherfaas.administrator.name"); // NOI18N
        xLabel20.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xLabel20);

        xLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel21.setCaption("Address");
        xLabel21.setCaptionWidth(100);
        xLabel21.setName("entity.motherfaas.administrator.address"); // NOI18N
        xLabel21.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xLabel21);

        xLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel16.setCaption(" PIN");
        xLabel16.setCaptionWidth(100);
        xLabel16.setName("entity.motherfaas.fullpin"); // NOI18N
        xLabel16.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xLabel16);

        xLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel25.setCaption("Cadastral Lot No.");
        xLabel25.setCaptionWidth(100);
        xLabel25.setName("entity.motherfaas.cadastrallotno"); // NOI18N
        xLabel25.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xLabel25);

        xLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel26.setCaption("Survey No.");
        xLabel26.setCaptionWidth(100);
        xLabel26.setName("entity.motherfaas.surveyno"); // NOI18N
        xLabel26.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xLabel26);

        xDecimalField1.setCaption(" Area (sqm)");
        xDecimalField1.setCaptionWidth(100);
        xDecimalField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        xDecimalField1.setEnabled(false);
        xDecimalField1.setName("entity.motherfaas.totalareasqm"); // NOI18N
        xDecimalField1.setPreferredSize(new java.awt.Dimension(150, 20));
        formPanel5.add(xDecimalField1);

        xDecimalField2.setCaption(" Area (ha)");
        xDecimalField2.setCaptionWidth(100);
        xDecimalField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        xDecimalField2.setEnabled(false);
        xDecimalField2.setName("entity.motherfaas.totalareaha"); // NOI18N
        xDecimalField2.setPattern("#,##0.000000");
        xDecimalField2.setPreferredSize(new java.awt.Dimension(150, 20));
        xDecimalField2.setScale(6);
        formPanel5.add(xDecimalField2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(formPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .add(formPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel16;
    private com.rameses.rcp.control.XLabel xLabel17;
    private com.rameses.rcp.control.XLabel xLabel18;
    private com.rameses.rcp.control.XLabel xLabel19;
    private com.rameses.rcp.control.XLabel xLabel20;
    private com.rameses.rcp.control.XLabel xLabel21;
    private com.rameses.rcp.control.XLabel xLabel25;
    private com.rameses.rcp.control.XLabel xLabel26;
    private com.rameses.rcp.control.XLabel xLabel3;
    // End of variables declaration//GEN-END:variables
    
}
