/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.queue.generator;

/**
 *
 * @author Dino Quimson
 */
public class CodeGeneratorPage extends javax.swing.JPanel {

    /**
     * Creates new form CodeGeneratorPage
     */
    public CodeGeneratorPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xButton1 = new com.rameses.rcp.control.XButton();

        xFormPanel1.setCaptionWidth(100);

        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("Section");
        xComboBox1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox1.setExpression("#{item.name}");
        xComboBox1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox1.setItems("sections");
        xComboBox1.setName("entity.section"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xIntegerField1.setText("xIntegerField1");
        xIntegerField1.setCaption("Quantity");
        xIntegerField1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xIntegerField1.setName("entity.quantity"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(80, 22));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xCheckBox1.setText("Continue Sequence");
        xCheckBox1.setCaption("");
        xCheckBox1.setName("entity.sequence"); // NOI18N
        xFormPanel1.add(xCheckBox1);

        xButton1.setText("Generate");
        xButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xButton1.setName("generate"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(xButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(xButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    // End of variables declaration//GEN-END:variables
}
