/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.waterworks.reading;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author Dino Quimson
 */
@Template(FormPage.class)
@StyleSheet
public class MeterReadingPage extends javax.swing.JPanel {

    /**
     * Creates new form MeterReadingPage
     */
    public MeterReadingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xLabel17 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel15 = new com.rameses.rcp.control.XLabel();
        xLabel16 = new com.rameses.rcp.control.XLabel();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xButton1 = new com.rameses.rcp.control.XButton();

        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "serialno"}
                , new Object[]{"caption", "Serial Number"}
                , new Object[]{"width", 200}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"alignment", "CENTER"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "currentreading"}
                , new Object[]{"caption", "Current Reading"}
                , new Object[]{"width", 130}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"alignment", "CENTER"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.IntegerColumnHandler(null, -1, -1)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "method"}
                , new Object[]{"caption", "Reading Method"}
                , new Object[]{"width", 130}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"alignment", "CENTER"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "reader.name"}
                , new Object[]{"caption", "Reading Officer"}
                , new Object[]{"width", 180}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"alignment", "CENTER"}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable1.setHandler("readingModel");
        xDataTable1.setName("reading"); // NOI18N

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("General Information");
        xPanel1.setBorder(xTitledBorder1);

        xFormPanel1.setCaptionWidth(130);
        xFormPanel1.setCellspacing(5);
        xFormPanel1.setPadding(new java.awt.Insets(5, 5, 5, 5));

        xLabel1.setBackground(new java.awt.Color(255, 255, 255));
        xLabel1.setCaption("Account No");
        xLabel1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel1.setDepends(new String[] {"reading"});
        xLabel1.setExpression("#{reading.acctno}");
        xLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel1.setOpaque(true);
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel1);

        xLabel2.setBackground(new java.awt.Color(255, 255, 255));
        xLabel2.setCaption("Owner");
        xLabel2.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel2.setDepends(new String[] {"reading"});
        xLabel2.setExpression("#{reading.name}");
        xLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel2.setOpaque(true);
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel2);

        xLabel8.setBackground(new java.awt.Color(255, 255, 255));
        xLabel8.setCaption("Serial No");
        xLabel8.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel8.setDepends(new String[] {"reading"});
        xLabel8.setExpression("#{reading.serialno}");
        xLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel8.setOpaque(true);
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel8);

        xLabel9.setBackground(new java.awt.Color(255, 255, 255));
        xLabel9.setCaption("Date Read");
        xLabel9.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel9.setDepends(new String[] {"reading"});
        xLabel9.setExpression("#{reading.dtread}");
        xLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel9.setOpaque(true);
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel9);

        xLabel10.setBackground(new java.awt.Color(255, 255, 255));
        xLabel10.setCaption("Year");
        xLabel10.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel10.setDepends(new String[] {"reading"});
        xLabel10.setExpression("#{reading.year}");
        xLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel10.setOpaque(true);
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel10);

        xLabel11.setBackground(new java.awt.Color(255, 255, 255));
        xLabel11.setCaption("Month");
        xLabel11.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel11.setDepends(new String[] {"reading"});
        xLabel11.setExpression("#{reading.monthstring}");
        xLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel11.setOpaque(true);
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel11);

        xLabel12.setBackground(new java.awt.Color(255, 255, 255));
        xLabel12.setCaption("Current Reading");
        xLabel12.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel12.setDepends(new String[] {"reading"});
        xLabel12.setExpression("#{reading.currentreading}");
        xLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel12.setOpaque(true);
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel12);

        xLabel17.setBackground(new java.awt.Color(255, 255, 255));
        xLabel17.setCaption("Previous Reading");
        xLabel17.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel17.setDepends(new String[] {"reading"});
        xLabel17.setExpression("#{reading.previousreading}");
        xLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel17.setOpaque(true);
        xLabel17.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel17);

        xLabel14.setBackground(new java.awt.Color(255, 255, 255));
        xLabel14.setCaption("Consumed");
        xLabel14.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel14.setDepends(new String[] {"reading"});
        xLabel14.setExpression("#{reading.consumed}");
        xLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel14.setOpaque(true);
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel14);

        xLabel15.setBackground(new java.awt.Color(255, 255, 255));
        xLabel15.setCaption("Reading Method");
        xLabel15.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel15.setDepends(new String[] {"reading"});
        xLabel15.setExpression("#{reading.method}");
        xLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel15.setOpaque(true);
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel15);

        xLabel16.setBackground(new java.awt.Color(255, 255, 255));
        xLabel16.setCaption("Read By");
        xLabel16.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel16.setDepends(new String[] {"reading"});
        xLabel16.setExpression("#{reading.reader.name}");
        xLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xLabel16.setOpaque(true);
        xLabel16.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel16);

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Search Option");
        xPanel2.setBorder(xTitledBorder2);

        xFormPanel3.setCaptionWidth(130);
        xFormPanel3.setCellspacing(5);
        xFormPanel3.setPadding(new java.awt.Insets(5, 5, 5, 5));

        xTextField1.setCaption("Account No");
        xTextField1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField1.setName("search.acctno"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xTextField1);

        xTextField2.setCaption("Serial No");
        xTextField2.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xTextField2.setName("search.serialno"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xTextField2);

        xComboBox3.setCaption("Route");
        xComboBox3.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox3.setName("search.route"); // NOI18N
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xComboBox3);

        xComboBox1.setCaption("Month");
        xComboBox1.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox1.setName("search.month"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 20));
        xFormPanel3.add(xComboBox1);

        xComboBox2.setCaption("Year");
        xComboBox2.setCaptionFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xComboBox2.setName("search.year"); // NOI18N
        xComboBox2.setPreferredSize(new java.awt.Dimension(100, 20));
        xFormPanel3.add(xComboBox2);

        xButton1.setCaption("");
        xButton1.setCellPadding(new java.awt.Insets(5, 0, 0, 0));
        xButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        xButton1.setName("search"); // NOI18N
        xButton1.setPreferredSize(new java.awt.Dimension(100, 25));
        xButton1.setText("Search");
        xFormPanel3.add(xButton1);

        javax.swing.GroupLayout xPanel2Layout = new javax.swing.GroupLayout(xPanel2);
        xPanel2.setLayout(xPanel2Layout);
        xPanel2Layout.setHorizontalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );
        xPanel2Layout.setVerticalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(xDataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xDataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel16;
    private com.rameses.rcp.control.XLabel xLabel17;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
