/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.rpt.rpu.ui;

import com.rameses.rcp.ui.annotations.StyleSheet;

@StyleSheet()
public class RpuInfoPreviousRecordPage extends javax.swing.JPanel {

    /**
     * Creates new form RpuInfoPreviousRecordPage
     */
    public RpuInfoPreviousRecordPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xFormPanel16 = new com.rameses.rcp.control.XFormPanel();
        xTextField27 = new com.rameses.rcp.control.XTextField();
        xTextField22 = new com.rameses.rcp.control.XTextField();
        xFormPanel14 = new com.rameses.rcp.control.XFormPanel();
        xDecimalField3 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField4 = new com.rameses.rcp.control.XDecimalField();
        xFormPanel15 = new com.rameses.rcp.control.XFormPanel();
        xDecimalField7 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField8 = new com.rameses.rcp.control.XDecimalField();
        xTextField23 = new com.rameses.rcp.control.XTextField();
        xTextField24 = new com.rameses.rcp.control.XTextField();

        xFormPanel2.setCaptionWidth(120);
        xFormPanel2.setCellspacing(1);
        xFormPanel2.setPadding(new java.awt.Insets(0, 5, 6, 5));

        xTextField13.setCaption("Previous TD No.");
        xTextField13.setCellPadding(new java.awt.Insets(0, 0, 2, 0));
        xTextField13.setMargin(new java.awt.Insets(1, 1, 1, 1));
        xTextField13.setName("entity.prevtdno"); // NOI18N
        xTextField13.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel2.add(xTextField13);

        xFormPanel16.setCaptionWidth(120);
        xFormPanel16.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel16.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel16.setPreferredSize(new java.awt.Dimension(0, 21));
        xFormPanel16.setShowCaption(false);

        xTextField27.setCaption("Prev. Effectivity");
        xTextField27.setCellPadding(new java.awt.Insets(0, 0, 0, 5));
        xTextField27.setMargin(new java.awt.Insets(1, 1, 1, 1));
        xTextField27.setName("entity.preveffectivity"); // NOI18N
        xFormPanel16.add(xTextField27);

        xTextField22.setCaption("Prev. PIN");
        xTextField22.setCaptionWidth(80);
        xTextField22.setCellPadding(new java.awt.Insets(0, 0, 2, 0));
        xTextField22.setMargin(new java.awt.Insets(1, 1, 1, 1));
        xTextField22.setName("entity.prevpin"); // NOI18N
        xTextField22.setStretchWidth(100);
        xFormPanel16.add(xTextField22);

        xFormPanel2.add(xFormPanel16);

        xFormPanel14.setCaptionWidth(120);
        xFormPanel14.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel14.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel14.setPreferredSize(new java.awt.Dimension(0, 21));
        xFormPanel14.setShowCaption(false);

        xDecimalField3.setCaption("Previous M.V.");
        xDecimalField3.setCellPadding(new java.awt.Insets(0, 0, 0, 5));
        xDecimalField3.setName("entity.prevmv"); // NOI18N
        xDecimalField3.setStretchWidth(50);
        xFormPanel14.add(xDecimalField3);

        xDecimalField4.setCaption("A.V.");
        xDecimalField4.setCaptionWidth(55);
        xDecimalField4.setName("entity.prevav"); // NOI18N
        xDecimalField4.setStretchWidth(50);
        xFormPanel14.add(xDecimalField4);

        xFormPanel2.add(xFormPanel14);

        xFormPanel15.setCaptionWidth(120);
        xFormPanel15.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel15.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel15.setPreferredSize(new java.awt.Dimension(0, 21));
        xFormPanel15.setShowCaption(false);

        xDecimalField7.setCaption("Prev. Area (sqm)");
        xDecimalField7.setCellPadding(new java.awt.Insets(0, 0, 0, 5));
        xDecimalField7.setName("entity.prevareasqm"); // NOI18N
        xDecimalField7.setStretchWidth(50);
        xFormPanel15.add(xDecimalField7);

        xDecimalField8.setCaption("(ha)");
        xDecimalField8.setCaptionWidth(55);
        xDecimalField8.setName("entity.prevareaha"); // NOI18N
        xDecimalField8.setPattern("#,##0.000000");
        xDecimalField8.setScale(6);
        xDecimalField8.setStretchWidth(50);
        xFormPanel15.add(xDecimalField8);

        xFormPanel2.add(xFormPanel15);

        xTextField23.setCaption("Previous Owner");
        xTextField23.setCellPadding(new java.awt.Insets(0, 0, 2, 0));
        xTextField23.setDepends(new String[] {"entity.owner.*"});
        xTextField23.setMargin(new java.awt.Insets(1, 1, 1, 1));
        xTextField23.setName("entity.prevowner"); // NOI18N
        xTextField23.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel2.add(xTextField23);

        xTextField24.setCaption("Previous Admin");
        xTextField24.setCellPadding(new java.awt.Insets(0, 0, 2, 0));
        xTextField24.setDepends(new String[] {"entity.administrator.*"});
        xTextField24.setMargin(new java.awt.Insets(1, 1, 1, 1));
        xTextField24.setName("entity.prevadministrator"); // NOI18N
        xTextField24.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel2.add(xTextField24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDecimalField xDecimalField3;
    private com.rameses.rcp.control.XDecimalField xDecimalField4;
    private com.rameses.rcp.control.XDecimalField xDecimalField7;
    private com.rameses.rcp.control.XDecimalField xDecimalField8;
    private com.rameses.rcp.control.XFormPanel xFormPanel14;
    private com.rameses.rcp.control.XFormPanel xFormPanel15;
    private com.rameses.rcp.control.XFormPanel xFormPanel16;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField22;
    private com.rameses.rcp.control.XTextField xTextField23;
    private com.rameses.rcp.control.XTextField xTextField24;
    private com.rameses.rcp.control.XTextField xTextField27;
    // End of variables declaration//GEN-END:variables
}
